In [29]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

In [30]:
sentences = [
    "I love this movie",
    "This movie is amazing",
    "I hate this movie",
    "This movie is boring"
]

In [31]:
print(sentences)

['I love this movie', 'This movie is amazing', 'I hate this movie', 'This movie is boring']


In [32]:
from tensorflow.keras.preprocessing.text import one_hot

In [33]:
vocab_size = 10000

onehot_repr = [one_hot(sentence, vocab_size) for sentence in sentences]

print(onehot_repr)

[[7093, 5090, 3633, 6192], [3633, 6192, 6571, 7316], [7093, 2971, 3633, 6192], [3633, 6192, 6571, 2617]]


In [34]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [35]:
embedded_docs = pad_sequences(
    onehot_repr,
    padding='pre'
)

print(embedded_docs)

[[7093 5090 3633 6192]
 [3633 6192 6571 7316]
 [7093 2971 3633 6192]
 [3633 6192 6571 2617]]


In [36]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

In [37]:
embedding_vector_features = 10

model = Sequential()

model.add(
    Embedding(
        input_dim=10000,
        output_dim=embedding_vector_features
    )
)

In [38]:
embedding_vector_features = 10

model = Sequential()

model.add(
    Embedding(
        input_dim=10000,
        output_dim=embedding_vector_features
    )
)

In [39]:
output = model(embedded_docs)

print(output.shape)

(4, 4, 10)


In [40]:
print(embedded_docs.shape)
print(output.shape)

(4, 4)
(4, 4, 10)


In [41]:
from tensorflow.keras.layers import SimpleRNN

model.add(SimpleRNN(5))

In [42]:
from tensorflow.keras.layers import Dense

model.add(Dense(1, activation='sigmoid'))

In [43]:
model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [44]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, None, 10)          100000    
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 5)                 80        
                                                                 
 dense_1 (Dense)             (None, 1)                 6         
                                                                 
Total params: 100086 (390.96 KB)
Trainable params: 100086 (390.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [45]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [46]:
y = [1, 1, 0, 0]

In [47]:
import numpy as np

In [48]:
y = np.array([1, 1, 0, 0])

In [49]:
np.array(embedded_docs).shape

(4, 4)

In [50]:
X = np.array(embedded_docs)
X.shape

(4, 4)

In [51]:
model.fit(
    X,
    y,
    epochs=5,
    batch_size=2
)

Epoch 1/5
2/2 [==============================] - 2s 8ms/step - loss: 0.7070 - accuracy: 0.5000
Epoch 2/5
2/2 [==============================] - 0s 8ms/step - loss: 0.7021 - accuracy: 0.5000
Epoch 3/5
2/2 [==============================] - 0s 9ms/step - loss: 0.7006 - accuracy: 0.5000
Epoch 4/5
2/2 [==============================] - 0s 10ms/step - loss: 0.6970 - accuracy: 0.5000
Epoch 5/5
2/2 [==============================] - 0s 89ms/step - loss: 0.6931 - accuracy: 0.5000


In [52]:
model.save("simple_rnn_imdb_relu.h5")

In [54]:
X_train.shape
y_train.shape

NameError: name 'X_train' is not defined

In [55]:
X_test.shape
y_test.shape

NameError: name 'X_test' is not defined

In [56]:
from tensorflow.keras.datasets import imdb

max_features = 10000

(X_train, y_train), (X_test, y_test) = imdb.load_data(
    num_words=max_features
)

17464789/17464789 [==============================] - 6s 0us/step


In [57]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(25000,)
(25000,)
(25000,)
(25000,)


In [58]:
X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1153, 194, 8255, 78, 228,

In [59]:
print("First review length:", len(X_train[0]))
print("Second review length:", len(X_train[1]))

First review length: 218
Second review length: 189


In [60]:
from tensorflow.keras.preprocessing import sequence

max_len = 500

X_train = sequence.pad_sequences(
    X_train,
    maxlen=max_len
)

X_test = sequence.pad_sequences(
    X_test,
    maxlen=max_len
)

In [61]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

X_train: (25000, 500)
X_test: (25000, 500)


In [62]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

model = Sequential()

model.add(Embedding(
    input_dim=10000,
    output_dim=10,
    input_length=500
))

model.add(SimpleRNN(5))

model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 500, 10)           100000    
                                                                 
 simple_rnn_2 (SimpleRNN)    (None, 5)                 80        
                                                                 
 dense_2 (Dense)             (None, 1)                 6         
                                                                 
Total params: 100086 (390.96 KB)
Trainable params: 100086 (390.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [63]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [64]:
history = model.fit(
    X_train,
    y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.2
)

Epoch 1/5
313/313 [==============================] - 35s 105ms/step - loss: 0.6861 - accuracy: 0.5413 - val_loss: 0.6734 - val_accuracy: 0.5798
Epoch 2/5
313/313 [==============================] - 27s 86ms/step - loss: 0.6106 - accuracy: 0.6903 - val_loss: 0.6551 - val_accuracy: 0.6042
Epoch 3/5
313/313 [==============================] - 26s 82ms/step - loss: 0.4824 - accuracy: 0.7951 - val_loss: 0.6876 - val_accuracy: 0.6058
Epoch 4/5
313/313 [==============================] - 26s 83ms/step - loss: 0.3641 - accuracy: 0.8637 - val_loss: 0.7656 - val_accuracy: 0.5870
Epoch 5/5
313/313 [==============================] - 26s 83ms/step - loss: 0.2766 - accuracy: 0.9074 - val_loss: 0.8473 - val_accuracy: 0.5868


In [66]:
loss, accuracy = model.evaluate(
    X_test,
    y_test,
    verbose=1
)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

782/782 [==============================] - 14s 18ms/step - loss: 0.9309 - accuracy: 0.5794
Test Loss: 0.9308807253837585
Test Accuracy: 0.5794000029563904


In [67]:
model.save("simple_rnn_imdb_relu.h5")

In [68]:
loss, accuracy = model.evaluate(
    X_test,
    y_test,
    verbose=1
)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

782/782 [==============================] - 16s 20ms/step - loss: 0.9309 - accuracy: 0.5794
Test Loss: 0.9308807253837585
Test Accuracy: 0.5794000029563904


In [71]:
import os

print(os.path.exists("simple_rnn_imdb_relu.h5"))

True


In [70]:
model.save("simple_rnn_imdb_relu.h5")